name: Build images and add to ghcr.io upon release
on:
  release:
    types:
      - published

jobs:
  webservice_image:
    name: Push webservice image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.0.0

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: webservice-meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            name=ghcr.io/belastingdienst/webservice,enable=true
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest
            type=sha

      - name: Build and push webservice image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ${{ steps.webservice-meta.outputs.tags }}
          labels: ${{ steps.webservice-meta.outputs.labels }}
          build-args: VERSION=${{ github.ref_name }}

      - name: Generate webservice image SBOM
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          image-ref: 'ghcr.io/belastingdienst/webservice'
          scan-type: image
          format: 'github'
          output: 'webservice_image.sbom.json'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          severity: 'MEDIUM,HIGH,CRITICAL'
          scanners: 'vuln'
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Add SBOM to release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: '${{ github.workspace }}/webservice_image.sbom.json'
